name: CI

on:
  push: 
    branches: main
  workflow_dispatch:
  pull_request:
    branches: main

jobs:
  build:
    name: Build & Tests
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Run build
        run: echo "Building..."
      - name: Run tests
        run: echo "Tests..."
      - name: Add tag
        if: github.ref == 'refs/heads/main'
        run: |
          buildDate=$(date +'%Y%m')
          echo "buildDate=$buildDate"

          runNumber=${GITHUB_RUN_NUMBER}
          echo "runNumber=$runNumber"

          tag="$buildDate.$runNumber"
          echo "tag: $tag"

          git tag $tag
          git push origin $tag
