name: Deploy to All

on:
  release:
    types: [published]

jobs:
  deploy-dev:
    name: Deploy to Develop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        run: echo "Deploying to Develop"
  
  integration-tests:
    name: Integration tests
    needs: [deploy-dev]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        run: echo "Deploying to Develop"

  
  deploy-staging:
    name: Deploy to Staging
    needs: [deploy-dev, integration-tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        run: echo "Deploying to Staging"

  deploy-sandbox:
    name: Deploy to Sandbox
    runs-on: ubuntu-latest
    needs: [deploy-dev, integration-tests, deploy-staging]
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        run: echo "Deploying to Sandbox"
  
  deploy-prod:
    name: Deploy to Prod
    runs-on: ubuntu-latest
    needs: [deploy-dev, integration-tests, deploy-staging]
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        run: echo "Deploying to Production"
