name: Deploy to Dev

on:
  release:
    types: [published]

jobs:
  deploy-dev:
    name: Deploy to Develop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        run: echo "Deploying to Develop"
  
  integration-tests:
    name: Integration tests
    needs: [deploy-dev]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        run: echo "Deploying to Develop"

  
  deploy-staging:
    name: Deploy to Staging
    needs: [deploy-dev, integration-tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        run: echo "Deploying to Staging"
